RST-1566: Bump rspec-rails from 3.8.0 to 3.8.1 (#2)
Bumps [rspec-rails](https://github.com/rspec/rspec-rails) from 3.8.0 to 3.8.1.
<details>
<summary>Changelog</summary>

*Sourced from [rspec-rails's changelog](https://github.com/rspec/rspec-rails/blob/master/Changelog.md).*

> ### 3.8.1 / 2018-10-23
> [Full Changelog](http://github.com/rspec/rspec-rails/compare/v3.8.0...v3.8.1)
> 
> Bug Fixes:
> 
> * Fix `NoMethodError: undefined method 'strip'` when using a `Pathname` object
>   as the fixture file path. (Aaron Kromer, [#2026](https://github-redirect.dependabot.com/rspec/rspec-rails/issues/2026))
> * When generating feature specs, do not duplicate namespace in the path name.
>   (Laura Paakkinen, [#2034](https://github-redirect.dependabot.com/rspec/rspec-rails/issues/2034))
> * Prevent `ActiveJob::DeserializationError` from being issued when `ActiveJob`
>   matchers de-serialize arguments. ([**aymeric-ledorze**](https://github.com/aymeric-ledorze), [#2036](https://github-redirect.dependabot.com/rspec/rspec-rails/issues/2036))
</details>
<details>
<summary>Commits</summary>

- [`64ea99f`](https://github.com/rspec/rspec-rails/commit/64ea99f2a95bf82ac421f25ad9ee48784300fb8d) Update version to 3.8.1
- [`09014f0`](https://github.com/rspec/rspec-rails/commit/09014f03902c5199e377fec18f41e214783d5e98) Changelog for [#2036](https://github-redirect.dependabot.com/rspec/rspec-rails/issues/2036)
- [`25c5843`](https://github.com/rspec/rspec-rails/commit/25c5843179b81b1b79b167fd485c43d3a555a884) Correct change log to indicate post v.3.8.0 fixes.
- [`cc7c714`](https://github.com/rspec/rspec-rails/commit/cc7c71451097d7b4cf837a4babbc98f94c12625e) Prevent ActiveJob::DeserializationError when deserialising expired jobs ([#2036](https://github-redirect.dependabot.com/rspec/rspec-rails/issues/2036))
- [`9af9514`](https://github.com/rspec/rspec-rails/commit/9af9514072b9373055f28f31238a51459591d35f) Merge pull request [#2034](https://github-redirect.dependabot.com/rspec/rspec-rails/issues/2034) from jekuta/fix-1877
- [`a9d7a6b`](https://github.com/rspec/rspec-rails/commit/a9d7a6b66923f17f725833f4c4bde2c3f519eb49) Udpate nokogiri version ([#2032](https://github-redirect.dependabot.com/rspec/rspec-rails/issues/2032))
- [`f061066`](https://github.com/rspec/rspec-rails/commit/f06106656530c37d6ffd4edf5fb7410b40831d72) Merge pull request [#2027](https://github-redirect.dependabot.com/rspec/rspec-rails/issues/2027) from benoittgt/bump_bundler_to_last_version_again
- [`8ae77c1`](https://github.com/rspec/rspec-rails/commit/8ae77c121d45d1ad376bef874293b3fd767732df) Merge pull request [#2026](https://github-redirect.dependabot.com/rspec/rspec-rails/issues/2026) from cupakromer/fix-nomethoderror-pathname-fixture-path
- [`124c82a`](https://github.com/rspec/rspec-rails/commit/124c82a4c8f10232e458fcf999e23ac43ff598cc) Add project metadata to the gemspec ([#2035](https://github-redirect.dependabot.com/rspec/rspec-rails/issues/2035))
- [`d05d6bd`](https://github.com/rspec/rspec-rails/commit/d05d6bd6d3a18f462881ce2a7583419d6da884e8) Updates maintenance-branch file.
- See full diff in [compare view](https://github.com/rspec/rspec-rails/compare/v3.8.0...v3.8.1)
</details>
<br />

[![Dependabot compatibility score](https://api.dependabot.com/badges/compatibility_score?dependency-name=rspec-rails&package-manager=bundler&previous-version=3.8.0&new-version=3.8.1)](https://dependabot.com/compatibility-score.html?dependency-name=rspec-rails&package-manager=bundler&previous-version=3.8.0&new-version=3.8.1)

Dependabot will resolve any conflicts with this PR as long as you don't alter it yourself. You can also trigger a rebase manually by commenting `@dependabot rebase`.

[//]: # (dependabot-automerge-start)
[//]: # (dependabot-automerge-end)

---

**Note:** This repo was added to Dependabot recently, so you'll receive a maximum of 5 PRs for your first few update runs. Once an update run creates fewer than 5 PRs we'll remove that limit.

You can always request more updates by clicking `Bump now` in your [Dependabot dashboard](https://app.dependabot.com).

<details>
<summary>Dependabot commands and options</summary>
<br />

You can trigger Dependabot actions by commenting on this PR:
- `@dependabot rebase` will rebase this PR
- `@dependabot recreate` will recreate this PR, overwriting any edits that have been made to it
- `@dependabot merge` will merge this PR after your CI passes on it
- `@dependabot cancel merge` will cancel a previously requested merge
- `@dependabot reopen` will reopen this PR if it is closed
- `@dependabot ignore this [patch|minor|major] version` will close this PR and stop Dependabot creating any more for this minor/major version (unless you reopen the PR or upgrade to it yourself)
- `@dependabot ignore this dependency` will close this PR and stop Dependabot creating any more for this dependency (unless you reopen the PR or upgrade to it yourself)
- `@dependabot use these labels` will set the current labels as the default for future PRs for this repo and language
- `@dependabot use these reviewers` will set the current reviewers as the default for future PRs for this repo and language
- `@dependabot use these assignees` will set the current assignees as the default for future PRs for this repo and language
- `@dependabot use this milestone` will set the current milestone as the default for future PRs for this repo and language
- `@dependabot badge me` will comment on this PR with code to add a "Dependabot enabled" badge to your readme

Additionally, you can set the following in your Dependabot [dashboard](https://app.dependabot.com):
- Update frequency (including time of day and day of week)
- Automerge options (never/patch/minor, and dev/runtime dependencies)
- Pull request limits (per update run and/or open at any time)
- Out-of-range updates (receive only lockfile updates, if desired)
- Security updates (receive only security updates, if desired)

Finally, you can contact us by mentioning @dependabot.

</details>